"""Centralized protection data for app, bundle, path, and uninstaller policies."""

from __future__ import annotations

from typing import Any

DEFAULT_PROTECTED_BUNDLE_IDS = (
    "com.apple.AddressBook",
    "com.apple.CalendarAgent",
    "com.apple.FaceTime",
    "com.apple.Home",
    "com.apple.Maps",
    "com.apple.MobileSMS",
    "com.apple.Notes",
    "com.apple.Passbook",
    "com.apple.Photos",
    "com.apple.Safari",
    "com.apple.Settings",
    "com.apple.SystemSettings",
    "com.apple.Spotlight",
    "com.apple.accountsd",
    "com.apple.akd",
    "com.apple.assistant",
    "com.apple.bird",
    "com.apple.bookmarks",
    "com.apple.calaccessd",
    "com.apple.cloudkit",
    "com.apple.contacts",
    "com.apple.findmy",
    "com.apple.iCal",
    "com.apple.iChat",
    "com.apple.iCloudDrive",
    "com.apple.iMessage",
    "com.apple.identityservicesd",
    "com.apple.imagent",
    "com.apple.mail",
    "com.apple.messages",
    "com.apple.notes",
    "com.apple.photoanalysisd",
    "com.apple.reminders",
    "com.apple.security",
    "com.apple.siri",
    "com.apple.soagent",
    "com.apple.suggestd",
    "com.apple.syncdefaultsd",
    "com.apple.telephonyutilities.callservicesd",
    "com.apple.tips",
    "com.apple.translationd",
    "com.apple.wallet",
    "com.apple.webapp",
    "com.apple.webkit",
    "com.apple.xpc.launchd",
    "com.apple.finder",
    "com.apple.dock",
    "com.apple.loginwindow",
    "com.apple.SystemUIServer",
    "com.apple.SecurityAgent",
    "com.apple.AppStore",
    "com.apple.Preview",
    "com.apple.TextEdit",
    "com.apple.KeychainAccess",
    "com.apple.systempreferences",
    "com.apple.systemsettings",
    "com.apple.controlcenter",
    "com.apple.notificationcenterui",
    "com.apple.backgroundtaskmanagementagent",
    "com.apple.sharedfilelist",
    "com.apple.Terminal",
    "com.apple.ActivityMonitor",
    "com.apple.Console",
    "com.apple.DiskUtility",
    "com.apple.keychainaccess",
    "com.google.Drive",
    "com.microsoft.OneDrive",
    "com.dropbox.DropboxMacUpdate",
    "com.getdropbox.dropbox",
    "com.backblaze.Backblaze",
    "com.1password.1password",
    "com.agilebits.onepassword7",
    "com.bitwarden.desktop",
    "com.dashlane.dashlanephonefinal",
    "com.lastpass.LastPass",
    "com.docker.docker",
    "com.orbstack.OrbStack",
    "com.tailscale.ipn.macos",
    "com.cloudflare.1dot1dot1dot1.macos",
    "org.pqrs.Karabiner-Elements",
    "im.rime.inputmethod.Squirrel",
    "com.anthropic.claudefordesktop",
    "com.openai.chat",
    "com.todesktop.230313mzl4w4u92",
    "com.cursor.Cursor",
    "com.ollama.ollama",
)


PROTECTED_BUNDLE_PREFIXES = ("com.apple.",)


APPLE_UNINSTALLABLE_BUNDLE_PATTERNS = (
    "com.apple.dt.*",
    "com.apple.FinalCut*",
    "com.apple.Motion",
    "com.apple.Compressor",
    "com.apple.logic*",
    "com.apple.garageband*",
    "com.apple.iMovie",
    "com.apple.iWork.*",
    "com.apple.MainStage*",
    "com.apple.server.*",
    "com.apple.Playgrounds",
)


SYSTEM_CRITICAL_BUNDLE_PATTERNS = (
    "com.apple.finder",
    "com.apple.dock",
    "com.apple.Safari",
    "com.apple.mail",
    "com.apple.systempreferences*",
    "com.apple.SystemSettings",
    "com.apple.Settings*",
    "com.apple.controlcenter*",
    "com.apple.Spotlight",
    "com.apple.notificationcenterui",
    "com.apple.loginwindow",
    "com.apple.Preview",
    "com.apple.TextEdit",
    "com.apple.Notes",
    "com.apple.reminders",
    "com.apple.iCal",
    "com.apple.AddressBook",
    "com.apple.Photos",
    "com.apple.AppStore",
    "com.apple.ActivityMonitor",
    "com.apple.Console",
    "com.apple.DiskUtility",
    "com.apple.KeychainAccess",
    "com.apple.Terminal",
    "com.apple.SecurityAgent",
    "com.apple.CoreServices*",
    "com.apple.SystemUIServer",
    "com.apple.backgroundtaskmanagement*",
    "com.apple.loginitems*",
    "com.apple.sharedfilelist*",
    "com.apple.sfl*",
    "com.apple.metadata*",
    "com.apple.MobileSoftwareUpdate*",
    "com.apple.SoftwareUpdate*",
    "com.apple.installer*",
    "com.apple.security*",
    "com.apple.keychain*",
    "com.apple.trustd*",
    "com.apple.securityd*",
    "com.apple.cloudd*",
    "com.apple.iCloud*",
    "com.apple.WiFi*",
    "com.apple.airport*",
    "com.apple.Bluetooth*",
    "com.apple.inputmethod.*",
    "com.apple.inputsource*",
    "com.apple.TextInput*",
    "com.apple.CharacterPicker*",
    "com.apple.PressAndHold*",
    "loginwindow",
    "dock",
    "systempreferences",
    "finder",
    "safari",
    "backgroundtaskmanagementagent",
    "keychain*",
    "security*",
    "bluetooth*",
    "wifi*",
    "network*",
    "tcc",
    "notification*",
    "accessibility*",
    "universalaccess*",
    "HIToolbox*",
    "textinput*",
    "TextInput*",
    "keyboard*",
    "Keyboard*",
    "inputsource*",
    "InputSource*",
    "keylayout*",
    "KeyLayout*",
    "GlobalPreferences",
    ".GlobalPreferences",
    "org.pqrs.Karabiner*",
)


DATA_PROTECTED_BUNDLE_PATTERNS = (
    "com.tencent.inputmethod.QQInput",
    "com.sogou.inputmethod.*",
    "com.baidu.inputmethod.*",
    "com.googlecode.rimeime.*",
    "im.rime.*",
    "*.inputmethod",
    "*.InputMethod",
    "*IME",
    "com.1password.*",
    "com.agilebits.*",
    "com.lastpass.*",
    "com.dashlane.*",
    "com.bitwarden.*",
    "com.keepassx.*",
    "org.keepassx.*",
    "org.keepassxc.*",
    "com.authy.*",
    "com.yubico.*",
    "com.jetbrains.*",
    "JetBrains*",
    "com.microsoft.VSCode",
    "com.visualstudio.code.*",
    "com.microsoft.VSCodeInsiders",
    "com.sublimetext.*",
    "com.sublimehq.*",
    "com.docker.*",
    "com.getpostman.*",
    "com.postmanlabs.mac",
    "com.insomnia.*",
    "com.konghq.insomnia",
    "com.todesktop.*",
    "Cursor",
    "com.cursor.*",
    "com.anthropic.claude*",
    "Claude",
    "com.openai.chat*",
    "ChatGPT",
    "com.openai.codex",
    "Codex",
    "codex-runtimes",
    "com.ollama.ollama",
    "Ollama",
    "com.lmstudio.lmstudio",
    "LM Studio",
    "co.supertool.chatbox",
    "page.jan.jan",
    "com.huggingface.huggingchat",
    "Gemini",
    "com.perplexity.Perplexity",
    "com.exafunction.windsurf",
    "com.quora.poe.electron",
    "com.nssurge.*",
    "com.v2ray.*",
    "com.clash.*",
    "com.clash.app",
    "ClashX*",
    "Surge*",
    "Shadowrocket*",
    "Quantumult*",
    "clash-*",
    "Clash-*",
    "*-clash",
    "*-Clash",
    "clash.*",
    "Clash.*",
    "clash_*",
    "*clash-verge*",
    "*Clash-Verge*",
    "clashverge*",
    "ClashVerge*",
    "com.tailscale.*",
    "io.tailscale.*",
    "com.cloudflare.*",
    "net.tunnelblick.*",
    "com.crowdstrike.*",
    "com.jamf.*",
    "com.jamfsoftware.*",
    "com.sentinelone.*",
    "com.sentinel-labs.*",
    "com.eset.*",
    "com.paloaltonetworks.*",
    "com.cisco.anyconnect*",
    "com.cisco.secureclient*",
)


CRITICAL_SYSTEM_PATHS_EXACT = (
    "/",
    "/bin",
    "/sbin",
    "/usr",
    "/usr/bin",
    "/usr/sbin",
    "/usr/lib",
    "/System",
    "/Library/Apple",
    "/Library",
    "/Library/Extensions",
    "/Library/Keychains",
    "/Applications",
    "/Applications/Finder.app",
    "/Applications/Safari.app",
    "/Users",
    "/Users/Shared",
    "/Users/Guest",
    "/private",
    "/etc",
    "/private/etc",
    "/var",
    "/var/db",
    "/var/audit",
    "/private/var",
    "/private/var/db",
    "/private/var/audit",
)


CRITICAL_SYSTEM_PATH_PREFIXES = (
    "/bin/",
    "/sbin/",
    "/usr/bin/",
    "/usr/sbin/",
    "/usr/lib/",
    "/System/",
    "/Library/Apple/",
    "/Library/Extensions/",
    "/Library/Keychains/",
    "/Applications/Finder.app/",
    "/Applications/Safari.app/",
    "/Users/Guest/",
    "/etc/",
    "/private/etc/",
    "/var/db/",
    "/var/audit/",
    "/private/var/db/",
    "/private/var/audit/",
)


SENSITIVE_USER_DATA_FRAGMENTS = (
    "/.ssh/",
    "/.gnupg/",
    "/library/keychains",
    "/library/mail/",
    "/library/messages/",
    "/library/application support/clouddocs",
    "/library/application support/com.apple.sharedfilelist",
    "/library/application support/com.apple.tcc",
    "/library/application support/*/credentials",
    "/library/application support/*/credential",
    "/library/application support/*/secrets",
    "/library/application support/*/tokens",
    "/library/application support/*/auth",
    "/library/application support/com.apple.controlcenter",
    "/library/application support/com.apple.systemsettings",
    "/library/application support/com.apple.systempreferences",
    "/library/tcc",
    "/library/preferences/.globalpreferences",
    "/library/preferences/globalpreferences",
    "/library/preferences/com.apple.dock.plist",
    "/library/preferences/com.apple.finder.plist",
    "/library/preferences/com.apple.security",
    "/library/preferences/com.apple.tcc",
    "/library/preferences/com.apple.networkextension",
    "/library/preferences/com.apple.vpn",
    "/library/preferences/com.apple.wifi",
    "/library/preferences/com.apple.bluetooth",
    "/library/preferences/com.apple.airport",
    "/library/preferences/com.apple.wireless",
    "/library/preferences/org.cups.printingprefs",
    "/library/preferences/org.pqrs.karabiner",
    "/library/preferences/systemconfiguration",
    "/library/preferences/byhost/com.apple.bluetooth",
    "/library/preferences/byhost/com.apple.wifi",
    "/library/group containers/group.com.apple.networkextension",
    "/library/application support/tunnelblick",
    "/library/application support/tailscale",
    "/library/application support/cloudflare",
    "/library/application support/clash",
    "/library/application support/clashx",
    "/library/application support/surge",
    "/library/application support/v2ray",
    "/library/application support/globalprotect",
    "/library/application support/cisco/anyconnect",
    "/library/application support/cisco/secure client",
    "/library/application support/crowdstrike",
    "/library/application support/jamf",
    "/library/application support/sentinelone",
    "/library/application support/sentinel labs",
    "/library/application support/eset",
    "/library/input methods",
    "/library/keyboard layouts",
    "/library/application support/rime",
    "/library/rime",
    "/.config/ibus/rime",
    "/library/application support/karabiner",
    "/library/application support/org.pqrs/karabiner",
    "/.config/karabiner",
    "/library/application support/1password",
    "/library/application support/bitwarden",
    "/library/application support/dashlane",
    "/library/application support/lastpass",
    "/library/application support/keepass",
    "/library/application support/keepassxc",
    "/library/application support/authy",
    "/library/application support/yubico",
    "/library/application support/dropbox",
    "/library/application support/google/drivefs",
    "/library/application support/jetbrains",
    "/library/preferences/jetbrains",
    "/library/application support/code/user/",
    "/.vscode/",
    "/.docker/",
    "/library/application support/postman",
    "/library/application support/insomnia",
    "/.claude/",
    "/.claude.json",
    "/.codex/",
    "/.cursor/",
    "/.ollama/",
    "/library/application support/claude",
    "/library/application support/cursor",
    "/library/application support/chatgpt",
    "/library/application support/com.openai.chat",
    "/library/application support/codex",
    "/library/application support/windsurf",
    "/library/application support/lm studio",
    "/library/application support/jan",
    "/library/application support/chatbox",
    "/library/application support/perplexity",
    "/library/application support/poe",
)


APPLE_CONTAINER_CACHE_EXCEPTIONS = (
    "/Data/Library/Caches/",
    "/Data/tmp/",
    "/Data/Library/Mail Downloads/",
)


OFFICIAL_UNINSTALLER_RULES: tuple[dict[str, str | tuple[str, ...]], ...] = (
    {"vendor": "ESET", "bundle_prefixes": ("com.eset.",), "name_fragments": ("eset",)},
    {
        "vendor": "Jamf",
        "bundle_prefixes": ("com.jamfsoftware.", "com.jamf."),
        "name_fragments": ("jamf", "self service"),
    },
    {"vendor": "CrowdStrike", "bundle_prefixes": ("com.crowdstrike.",), "name_fragments": ("crowdstrike", "falcon")},
    {
        "vendor": "SentinelOne",
        "bundle_prefixes": ("com.sentinelone.", "com.sentinel-labs."),
        "name_fragments": ("sentinelone", "sentinel one", "sentinel agent"),
    },
    {
        "vendor": "GlobalProtect",
        "bundle_prefixes": ("com.paloaltonetworks.",),
        "name_fragments": ("globalprotect", "global protect", "globalprotect.app"),
    },
    {
        "vendor": "Cisco",
        "bundle_prefixes": ("com.cisco.anyconnect", "com.cisco.secureclient", "com.cisco."),
        "name_fragments": ("cisco secure client", "cisco anyconnect", "anyconnect", "secure client"),
    },
)


APP_CLEANUP_RULES: dict[str, dict[str, Any]] = {
    "androidStudio": {
        "title": "Android Studio caches",
        "paths": (
            "~/Library/Caches/Google/AndroidStudio*/",
            "~/Library/Logs/Google/AndroidStudio*/",
            "~/Library/Application Support/Google/AndroidStudio*/caches/",
        ),
        "protected_patterns": ("*.jks", "*.keystore", "*/Android/Sdk/*", "*/.android/avd/*"),
    },
    "jetbrains": {
        "title": "JetBrains IDE caches",
        "paths": ("~/Library/Caches/JetBrains/*/", "~/Library/Logs/JetBrains/*/"),
        "protected_patterns": ("*/options/*", "*/eval/*"),
    },
    "vscode": {
        "title": "VS Code caches",
        "paths": ("~/Library/Application Support/Code/Cache/", "~/Library/Application Support/Code/CachedData/"),
        "protected_patterns": ("*/User/*", "*/workspaceStorage/*"),
    },
    "docker": {
        "title": "Docker desktop caches",
        "paths": ("~/Library/Caches/com.docker.docker/", "~/.docker/buildx/cache/"),
        "protected_patterns": ("~/.docker/config.json", "~/.docker/contexts/*", "~/.docker/daemon.json"),
    },
    "raycast": {"title": "Raycast caches", "paths": ("~/Library/Caches/com.raycast.macos/",)},
    "unity": {
        "title": "Unity caches",
        "paths": ("~/Library/Unity/cache/", "~/Library/Caches/com.unity3d.UnityEditor*/"),
    },
    "unreal": {
        "title": "Unreal Engine caches",
        "paths": ("~/Library/Application Support/Epic/UnrealEngine/Common/DerivedDataCache/",),
    },
    "godot": {"title": "Godot editor caches", "paths": ("~/Library/Application Support/Godot/cache/",)},
    "deveco": {
        "title": "DevEco Studio caches",
        "paths": ("~/Library/Caches/Huawei/DevEcoStudio*/", "~/Library/Logs/Huawei/DevEcoStudio*/"),
    },
    "maestro": {"title": "Maestro caches", "paths": ("~/.maestro/cache/", "~/Library/Caches/maestro/")},
    "chrome": {
        "title": "Chrome browser caches",
        "paths": (
            "~/Library/Caches/Google/Chrome/*/Cache/",
            "~/Library/Application Support/Google/Chrome/*/Cache/",
            "~/Library/Application Support/Google/Chrome/*/Code Cache/",
            "~/Library/Application Support/Google/Chrome/*/GPUCache/",
            "~/Library/Application Support/Google/Chrome/*/Service Worker/CacheStorage/",
        ),
        "protected_patterns": (
            "*/Bookmarks*",
            "*/Cookies*",
            "*/History*",
            "*/Login Data*",
            "*/Preferences",
            "*/Local State",
            "*/Extensions/*",
        ),
    },
    "edge": {
        "title": "Microsoft Edge browser caches",
        "paths": (
            "~/Library/Application Support/Microsoft Edge/*/Cache/",
            "~/Library/Application Support/Microsoft Edge/*/Code Cache/",
            "~/Library/Application Support/Microsoft Edge/*/GPUCache/",
            "~/Library/Application Support/Microsoft Edge/*/Service Worker/CacheStorage/",
            "~/Library/Caches/Microsoft Edge/",
        ),
        "protected_patterns": (
            "*/Bookmarks*",
            "*/Cookies*",
            "*/History*",
            "*/Login Data*",
            "*/Preferences",
            "*/Local State",
            "*/Extensions/*",
            "*/Local Storage/*",
            "*/IndexedDB/*",
        ),
    },
    "brave": {
        "title": "Brave browser caches",
        "paths": (
            "~/Library/Application Support/BraveSoftware/Brave-Browser/*/Cache/",
            "~/Library/Application Support/BraveSoftware/Brave-Browser/*/Code Cache/",
            "~/Library/Application Support/BraveSoftware/Brave-Browser/*/GPUCache/",
            "~/Library/Application Support/BraveSoftware/Brave-Browser/*/Service Worker/CacheStorage/",
            "~/Library/Caches/BraveSoftware/",
        ),
        "protected_patterns": (
            "*/Bookmarks*",
            "*/Cookies*",
            "*/History*",
            "*/Login Data*",
            "*/Preferences",
            "*/Local State",
            "*/Extensions/*",
            "*/Local Storage/*",
            "*/IndexedDB/*",
        ),
    },
    "arc": {
        "title": "Arc browser caches",
        "paths": (
            "~/Library/Application Support/Arc/User Data/*/Cache/",
            "~/Library/Application Support/Arc/User Data/*/Code Cache/",
            "~/Library/Application Support/Arc/User Data/*/GPUCache/",
            "~/Library/Application Support/Arc/User Data/*/Service Worker/CacheStorage/",
            "~/Library/Caches/company.thebrowser.Browser/",
        ),
        "protected_patterns": (
            "*/Bookmarks*",
            "*/Cookies*",
            "*/History*",
            "*/Login Data*",
            "*/Preferences",
            "*/Local State",
            "*/Extensions/*",
            "*/Local Storage/*",
            "*/IndexedDB/*",
        ),
    },
    "firefox": {
        "title": "Firefox browser caches",
        "paths": (
            "~/Library/Caches/Firefox/Profiles/*/cache2/entries/",
            "~/Library/Application Support/Firefox/Profiles/*/cache2/entries/",
            "~/Library/Application Support/Firefox/Profiles/*/startupCache/",
        ),
        "protected_patterns": (
            "*/places.sqlite",
            "*/cookies.sqlite",
            "*/logins.json",
            "*/key4.db",
            "*/cert9.db",
            "*/extensions/*",
            "*/prefs.js",
        ),
    },
    "discord": {
        "title": "Discord caches",
        "paths": (
            "~/Library/Application Support/discord/Cache/",
            "~/Library/Application Support/discord/Code Cache/",
            "~/Library/Application Support/discord/GPUCache/",
            "~/Library/Application Support/discord/Service Worker/CacheStorage/",
            "~/Library/Application Support/Discord/Cache/",
            "~/Library/Application Support/Discord/Code Cache/",
            "~/Library/Application Support/Discord/GPUCache/",
            "~/Library/Application Support/Discord/Service Worker/CacheStorage/",
            "~/Library/Caches/com.hnc.Discord/",
        ),
        "protected_patterns": (
            "*/Cookies*",
            "*/Local Storage/*",
            "*/IndexedDB/*",
            "*/storage/*",
            "*/Session Storage/*",
        ),
    },
    "notion": {
        "title": "Notion caches",
        "paths": (
            "~/Library/Application Support/Notion/Cache/",
            "~/Library/Application Support/Notion/Code Cache/",
            "~/Library/Application Support/Notion/GPUCache/",
            "~/Library/Application Support/Notion/Service Worker/CacheStorage/",
            "~/Library/Caches/notion.id/",
        ),
        "protected_patterns": (
            "*/Cookies*",
            "*/Local Storage/*",
            "*/IndexedDB/*",
            "*/databases/*",
            "*/storage/*",
        ),
    },
    "slack": {
        "title": "Slack caches",
        "paths": (
            "~/Library/Application Support/Slack/Cache/",
            "~/Library/Application Support/Slack/Code Cache/",
            "~/Library/Application Support/Slack/GPUCache/",
            "~/Library/Application Support/Slack/Service Worker/CacheStorage/",
            "~/Library/Caches/com.tinyspeck.slackmacgap/",
        ),
        "protected_patterns": ("*/Cookies*", "*/Local Storage/*", "*/IndexedDB/*", "*/storage/*"),
    },
    "zoom": {
        "title": "Zoom caches",
        "paths": ("~/Library/Application Support/zoom.us/data/Cache/", "~/Library/Caches/us.zoom.xos/"),
        "protected_patterns": ("*/Cookies*", "*/data/zoomus.enc.db", "*/data/zoomus.db"),
    },
    "teams": {
        "title": "Microsoft Teams caches",
        "paths": (
            "~/Library/Application Support/Microsoft/Teams/Cache/",
            "~/Library/Application Support/Microsoft/Teams/Code Cache/",
            "~/Library/Application Support/Microsoft/Teams/GPUCache/",
            "~/Library/Application Support/Microsoft/Teams/Service Worker/CacheStorage/",
            "~/Library/Application Support/Microsoft/Teams/Application Cache/",
        ),
        "protected_patterns": ("*/Cookies*", "*/Local Storage/*", "*/IndexedDB/*", "*/storage/*"),
    },
    "nodePackageCaches": {
        "title": "Node package manager caches",
        "paths": ("~/.npm/_cacache/", "~/Library/pnpm/store/", "~/Library/Caches/Yarn/"),
        "protected_patterns": ("~/.npmrc", "~/.yarnrc", "~/.yarnrc.yml", "~/Library/pnpm/rc"),
    },
    "pythonPackageCaches": {
        "title": "Python package manager caches",
        "paths": ("~/Library/Caches/pip/", "~/Library/Caches/pypoetry/", "~/Library/Caches/pdm/"),
        "protected_patterns": ("~/.pypirc", "~/Library/Application Support/pypoetry/auth.toml"),
    },
    "goBuildCaches": {
        "title": "Go build and module download caches",
        "paths": ("~/Library/Caches/go-build/", "~/go/pkg/mod/cache/download/"),
        "protected_patterns": ("~/.netrc", "~/.gitconfig", "~/go/env"),
    },
    "homebrewCaches": {
        "title": "Homebrew download caches",
        "paths": ("~/Library/Caches/Homebrew/",),
        "protected_patterns": ("/opt/homebrew/*", "/usr/local/Homebrew/*"),
    },
    "gradleCaches": {
        "title": "Gradle caches",
        "paths": ("~/.gradle/caches/", "~/.gradle/wrapper/dists/"),
        "protected_patterns": ("~/.gradle/gradle.properties", "~/.gradle/init.gradle", "~/.gradle/init.d/*"),
    },
    "cargoCaches": {
        "title": "Cargo registry and git caches",
        "paths": ("~/.cargo/registry/cache/", "~/.cargo/git/checkouts/", "~/.cargo/git/db/"),
        "protected_patterns": ("~/.cargo/credentials", "~/.cargo/config", "~/.cargo/config.toml"),
    },
    "cocoaPodsCaches": {
        "title": "CocoaPods caches",
        "paths": ("~/Library/Caches/CocoaPods/", "~/.cocoapods/repos/"),
        "protected_patterns": ("~/.netrc", "~/.gem/credentials", "~/.cocoapods/config.yaml"),
    },
    "postman": {
        "title": "Postman caches",
        "paths": (
            "~/Library/Application Support/Postman/Cache/",
            "~/Library/Application Support/Postman/Code Cache/",
            "~/Library/Caches/Postman/",
        ),
        "protected_patterns": ("*/IndexedDB/*", "*/Local Storage/*", "*/Cookies*", "*/workspaceStorage/*"),
    },
    "insomnia": {
        "title": "Insomnia caches",
        "paths": (
            "~/Library/Application Support/Insomnia/Cache/",
            "~/Library/Application Support/Insomnia/Code Cache/",
            "~/Library/Caches/Insomnia/",
        ),
        "protected_patterns": ("*/insomnia.*.db", "*/Local Storage/*", "*/Cookies*"),
    },
    "aiToolCaches": {
        "title": "AI tool caches",
        "paths": (
            "~/Library/Application Support/Claude/Cache/",
            "~/Library/Application Support/Claude/Code Cache/",
            "~/Library/Application Support/Cursor/Cache/",
            "~/Library/Application Support/Cursor/CachedData/",
            "~/Library/Application Support/Windsurf/Cache/",
            "~/Library/Application Support/Windsurf/CachedData/",
            "~/Library/Application Support/Windsurf/Code Cache/",
            "~/Library/Application Support/Windsurf/GPUCache/",
            "~/Library/Application Support/Windsurf/Service Worker/CacheStorage/",
            "~/Library/Application Support/ChatGPT/Cache/",
            "~/Library/Caches/com.openai.chat/",
            "~/.ollama/models/.cache/",
        ),
        "protected_patterns": (
            "~/.claude/*",
            "~/.codex/*",
            "~/.cursor/*",
            "~/.ollama/id_*",
            "~/.ollama/config*",
            "*/Application Support/Claude/*/storage/*",
            "*/Application Support/Cursor/User/*",
            "*/Application Support/Windsurf/User/*",
            "*/Application Support/Windsurf/Local Storage*",
            "*/Application Support/Windsurf/IndexedDB/*",
            "*/Application Support/Windsurf/*/Local Storage*",
            "*/Application Support/Windsurf/*/IndexedDB/*",
            "*/Application Support/ChatGPT/Local Storage/*",
            "*/Application Support/ChatGPT/IndexedDB/*",
        ),
    },
    "windsurf": {
        "title": "Windsurf caches",
        "paths": (
            "~/Library/Application Support/Windsurf/Cache/",
            "~/Library/Application Support/Windsurf/CachedData/",
            "~/Library/Application Support/Windsurf/Code Cache/",
            "~/Library/Application Support/Windsurf/GPUCache/",
            "~/Library/Application Support/Windsurf/Service Worker/CacheStorage/",
        ),
        "protected_patterns": (
            "*/Application Support/Windsurf/User/*",
            "*/Application Support/Windsurf/Local Storage*",
            "*/Application Support/Windsurf/IndexedDB/*",
            "*/Application Support/Windsurf/*/Local Storage*",
            "*/Application Support/Windsurf/*/IndexedDB/*",
            "*/Cookies*",
            "*/storage/*",
        ),
    },
}
